import javax.swing.*;
import javax.swing.plaf.basic.BasicToolBarUI;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.awt.Desktop;

public class WebPage {

    private JButton tikla_butonu;
    private JPanel panelMain;
    private JTextField web_sayfasi;
    private int say = 0;


    public WebPage() {
        tikla_butonu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // say++;
                // System.out.println("Butona " + say + " kez tıklandı.");

                String internet_adresi = web_sayfasi.getText().trim();
                if (!internet_adresi.startsWith("http://") && !internet_adresi.startsWith("https://")) {
                    internet_adresi = "https://" + internet_adresi;
                }

                Desktop d = Desktop.getDesktop();

                try {
                    d.browse(new URI(internet_adresi));
                } catch (IOException ex) {
                    System.out.printf("URL açılırken exception oluştu.");
                } catch (URISyntaxException ex) {
                    System.out.printf("URI Syntax Exception oluştu.");
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("WebPage");
        frame.setContentPane(new WebPage().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tikla_butonu = new JButton();
        tikla_butonu.setText("Tıkla");
        panelMain.add(tikla_butonu, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        web_sayfasi = new JTextField();
        panelMain.add(web_sayfasi, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
